version: '3.8'

services:
  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx:/etc/nginx/conf.d
      - ./certbot/www:/var/www/certbot
      - ./certbot/letsencrypt:/etc/letsencrypt
    depends_on:
      - portfolio
    restart: always

  portfolio:
    image: alvarosg97/portfolio:0f3ae9851e27d62891a6c5e77752edba47d939ef
    container_name: portfolio
    ports:
      - "3000:3000"
    restart: always

  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - ./certbot/www:/var/www/certbot
      - ./certbot/letsencrypt:/etc/letsencrypt
    command: certonly --webroot --webroot-path=/var/www/certbot --email alvarosanchezgon1997@gmail.com --agree-tos --no-eff-email -d asgdevops.eu
