on:
  push:
    branches-ignore:
      - master

name: CI-CD
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: alvarosg97/portfolio:${{ github.sha }}
          platforms: linux/amd64,linux/arm64

  deploy:
    needs: docker
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: 'latest'

      - name: Set up DigitalOcean kubeconfig
        run: |
          mkdir -p $HOME/.kube
          echo "${{ secrets.DIGITALOCEAN_KUBECONFIG }}" > $HOME/.kube/config
          chmod 600 $HOME/.kube/config

      - name: Deploy to DigitalOcean Kubernetes
        run: |
          kubectl set image deployment/portfolio portfolio=alvarosg97/portfolio:${{ github.sha }}
          kubectl rollout status deployment/portfolio
