name: CI-CD

on:
  push:
    branches-ignore:
      - master

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        run: |
          docker build -t alvarosg97/portfolio:${{ github.sha }} .
          docker push alvarosg97/portfolio:${{ github.sha }}
          docker tag alvarosg97/portfolio:${{ github.sha }} alvarosg97/portfolio:latest
          docker push alvarosg97/portfolio:latest

  deploy:
    name: deploy
    runs-on: ubuntu-latest
    needs: docker
    env:
      AWS_SECURITY_GROUP_ID: ${{ secrets.AWS_SECURITY_GROUP_ID }}
    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Get runner IP address
        id: ip
        uses: haythem/public-ip@v1.2

      - name: Whitelist runner IP address
        run: |
          aws ec2 authorize-security-group-ingress \
            --group-id $AWS_SECURITY_GROUP_ID \
            --protocol tcp \
            --port 22 \
            --cidr ${{ steps.ip.outputs.ipv4 }}/32

      - name: SSH into EC2 and deploy
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          port: ${{ secrets.EC2_PORT }}
          script: |
            cd /home/ubuntu/
            sudo docker pull alvarosg97/portfolio:${{ github.sha }}
            
            # Obtener el ID de la imagen antigua (excepto la nueva)
            OLD_IMAGE_ID=$(docker images alvarosg97/portfolio --format "{{.ID}}" | tail -n +2)

            # Detener los contenedores actuales
            docker-compose down

            # Eliminar la imagen antigua
            if [ -n "$OLD_IMAGE_ID" ]; then
              sudo docker rmi -f $OLD_IMAGE_ID
            fi

            # Actualizar la imagen en docker-compose.yaml
            sed -i "s|image: alvarosg97/portfolio:.*|image: alvarosg97/portfolio:${{ github.sha }}|g" docker-compose.yaml

            # Levantar los nuevos contenedores
            docker-compose up -d


      - name: Revoke runner IP address (always run)
        if: always()
        run: |
          aws ec2 revoke-security-group-ingress \
            --group-id $AWS_SECURITY_GROUP_ID \
            --protocol tcp \
            --port 22 \
            --cidr ${{ steps.ip.outputs.ipv4 }}/32
